View the buoy on RViz
osrf/buoy_entrypoint pull request #6
Opened 2022-05-25 03:03 UTC by quarkytale

Adding [sdformat_urdf](https://github.com/ros/sdformat_urdf) to the project

2022-05-25 21:07 UTC, quarkytale commented
Installing from source might not be required if we just end up using the binaries

2022-06-03 00:43 UTC, chapulina commented
It turns out that we should actually be compiling `sdformat_urdf` from source instead of using the debs. The debs are being compiled against Citadel 😱 , and we need to use then with Fortress. I opened this PR upstream to add Fortress support from source:

* https://github.com/ros/sdformat_urdf/pull/8

Once that's merged, we should be able to use the `galactic` branch here, as this PR is suggesting. We'll just need to also set `GAZEBO_VERSION=fortress` next to `IGNITION_VERSION` in these places:

https://github.com/osrf/buoy_entrypoint/blob/f8cf6f312c4c5cf64d23ed73a149bb23ec1403ed/docker/buoy/Dockerfile#L11

https://github.com/osrf/buoy_entrypoint/blob/f8cf6f312c4c5cf64d23ed73a149bb23ec1403ed/README.md#L50

2022-06-06 19:15 UTC, chapulina requested changes
LGTM after `GZ_VERSION` is added to the places suggested above.

* We also need https://github.com/ros/sdformat_urdf/pull/8 or equivalent merged upstream.

2022-06-13 21:49 UTC, chapulina approved these changes

2022-06-13 21:49 UTC, merged